// src/components/atoms/button.jsx
/**
 * @typedef Props - Props para el boton.
 * @property {React.ReactNode} children - Contenido interno del boton.
 * @property {React.MouseEventHandler<HTMLButtonElement>} onClick - Manejador de click.
 * @property {string} [className] - Clases CSS para el boton.
 */

/**
 * Boton reutilizable que acepta contenido interno, un manejador de click y clases CSS opcionales.
 * @param {Props} param0 
 * @returns {React.ReactElement} - Un elemento de boton con el contenido y comportamiento especificados.
 */
export default function Button({ children, onClick, className }) {
    return (
        <button
            onClick={onClick}
            className={`${className?.trim() || ''}`}
        >
            {children}
        </button>
    );
}

// src/components/atoms/button.svelte
<!-- @component Boton reutilizable que acepta contenido interno, un manejador de click y clases CSS opcionales. -->

<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLButtonAttributes } from "svelte/elements";
    /**
     * Props para el boton.
     */
    interface Props extends HTMLButtonAttributes {
        /**
         * Clases CSS para el boton.
         */
        class?: string;
        /**
         * Contenido interno del boton.
         */
        children: Snippet;
    }
    let { class: className, children, ...rest }: Props = $props();
</script>

<button class={`${className?.trim() || ""}`} {...rest}>
    {@render children()}
</button>
