// src/components/organisms/navbar.jsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import styles from '../../styles/navbar.module.css';

export default function Navbar() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    const session = localStorage.getItem('session');
    setIsLoggedIn(Boolean(session));

    const handleSessionChange = () => {
      const session = localStorage.getItem('session');
      setIsLoggedIn(Boolean(session));
    };

    window.addEventListener('sessionChanged', handleSessionChange);
    return () => window.removeEventListener('sessionChanged', handleSessionChange);
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('session');
    setIsLoggedIn(false);
    alert('Sesión cerrada');
  };

  return (
    <nav className={styles.navbar}>
      <Link href="/">
        <div className={styles.logo}>Anti-Infernum</div>
      </Link>
      <div className={styles.navLinks}>
        <div className={styles.link}>Incendios</div>
        <div className={styles.link}>Lugares Seguros</div>
        <div className={styles.link}>Alertas</div>
        {!isLoggedIn ? (
          <>
            <Link href="/login">
              <div className={styles.link}>Login</div>
            </Link>
            <Link href="/register">
              <button className={styles.loginBtn}>
                Regístrate
              </button>
            </Link>
          </>
        ) : (
          <button className={styles.loginBtn} onClick={handleLogout}>
            Cerrar Sesión
          </button>
        )}
      </div>
    </nav>
  );
}

// src/components/organisms/navbar.svelte
<script lang="ts">
    import Button from "@/components/atoms/button.svelte";
    import "@/styles/navbar.css";

    let isLoggedIn = $state(false);

    $effect(() => {
        const checkSession = () => {
            isLoggedIn = Boolean(localStorage.getItem("session"));
        };

        checkSession();

        window.addEventListener("sessionChanged", checkSession);

        return () => window.removeEventListener("sessionChanged", checkSession);
    });

    function handleLogout() {
        localStorage.removeItem("session");
        isLoggedIn = false;
        alert("Sesion cerrada");

        window.dispatchEvent(new Event("sessionChanged"));
    }
</script>

<nav class="navbar">
    <a class="logo" href="/">
        <div>Anti-Infernum</div>
    </a>

    <div class="navLinks">
        <div class="link">Incendios</div>
        <div class="link">Lugares Seguros</div>
        <div class="link">Alertas</div>

        {#if !isLoggedIn}
            <a href="/login">
                <div class="link">LOGIN</div>
            </a>
            <a href="/register">
                <div class="loginBtn">Registrate</div>
            </a>
        {:else}
            <Button class="loginBtn" onclick={handleLogout}
                >Cerrar Sesion</Button
            >
        {/if}
    </div>
</nav>
