// src/routes/register/+page.svelte
<script lang="ts">
    import { enhance } from "$app/forms";
    import { goto } from "$app/navigation";
    import Button from "@/components/atoms/button.svelte";
    import "@/styles/register.css";

    let loading = $state(false);
    let error = $state("");

    function handleEnhance() {
        error = "";
        loading = true;

        return async ({ result, update }: any) => {
            loading = false;

            if (result?.type === "success") {
                alert("Usuario registrado exitosamente. Redirigiendo a login...");
                await goto("/login");
                return;
            }

            if (result?.type === "failure") {
                error = result?.data?.error ?? "Credenciales inválidas.";
                await update?.();
                return;
            }

            if (result?.type === "error") {
                error = "Error de login. Intenta de nuevo.";
                await update?.();
            }
        };
    }
</script>

<svelte:head>
    <title>anti-infernum - Gestión de Incendios | Registro de sesion</title>
</svelte:head>

<div class="addUser">
    <h3>Registro</h3>

    <form
        class="addUserForm"
        method="POST"
        action="?/register"
        use:enhance={handleEnhance}
    >
        <div class="inputGroup">
            <label for="name">Nombre:</label>
            <input
                name="name"
                type="name"
                placeholder="Ingresa tu nombre"
            />

            <label for="email">Email:</label>
            <input
                name="email"
                type="email"
                placeholder="Ingresa tu email"
            />

            <label for="password">Contrasena:</label>
            <input
                name="password"
                type="password"
                placeholder="Ingresa una contrasena super segura 👌"
            />

            <label for="confirmPassword">Confirma la contrasena:</label>
            <input
                name="confirmPassword"
                type="password"
                placeholder="Confirma tu contrasena super segura 👌"
            />

            {#if error}
                <p class="error">{error}</p>
            {/if}

            <Button type="submit" class="loginBtn" disabled={loading}>
                {loading ? "Registrando..." : "Registrar"}
            </Button>
        </div>
    </form>

    <div class="login">
        <p>Ya tienes una cuenta?</p>
        <a href="/login">
            <Button class="loginBtn">Ingresa</Button>
        </a>
    </div>
</div>

// src/app/register/page.jsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import styles from '../../styles/register.module.css';
import { addUser, findUserByEmail } from '../../data/users';
//esto era para probar usuarios locales, pero no alcanzamos a hacerlo xd 👀👀👀
//necesito contexto de ese void

export default function RegisterPage() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleRegister = () => {
    const exists = findUserByEmail(email);

    if (exists) {
      setError('Este correo ya está registrado. Inicia sesión.');
      return;
    }

    addUser({ name, email, password });
    setError('');
    alert('Registro exitoso');
  };

  return (
    <div className={styles.addUser}>
      <h3>Sign Up</h3>

      <form className={styles.addUserForm}>
        <div className={styles.inputGroup}>
          <label>Nombre:</label>
          <input
            type="text"
            placeholder="Ingresa tu nombre"
            onChange={(e) => setName(e.target.value)}
          />

          <label>Email:</label>
          <input
            type="email"
            placeholder="Ingresa tu email"
            onChange={(e) => setEmail(e.target.value)}
          />

          <label>Contraseña:</label>
          <input
            type="password"
            placeholder="Ingresa tu contraseña super segura 👌"
            onChange={(e) => setPassword(e.target.value)}
          />

          {error && <p className={styles.error}>{error}</p>}

          <button type="button" className={styles.loginBtn} onClick={handleRegister}>
            Registrar
          </button>
        </div>
      </form>

      <div className={styles.login}>
        <p>Ya tienes una cuenta?</p>
        <button className={styles.loginBtn}>
            Login
        </button>
      </div>
    </div>
  );
}
